{
 "title": "OS stats - Linux",
 "description": "Presentation of OS metrics collected from Metricbeat. Also including logs for correlation with logs from filebeat.",
 "tags": [
  "metricbeat",
  "linux"
 ],
 "time": { "from": "now-1h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "Host",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\",\"size\":2000, \"query\": \"host.name:* AND NOT host.os.family:windows\"} "
   },
   {
    "name": "interval",
    "label": "Resolution",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "SERVER OVERVIEW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 6, "x": 1, "y": 1 },
     "content": "<h3><center><strong>$HOST</strong> <small><strong><br>IT-Infrastructure</strong></small></center></h3>\n\n\n",
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1381",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:1379", "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:674",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:612",
         "field": "system.uptime.duration.ms",
         "id": "1",
         "meta": {},
         "pipelineVariables": [
          { "$$hashKey": "object:657", "name": "var2", "pipelineAgg": "select metric" }
         ],
         "settings": {},
         "type": "max"
        }
       ],
       "query": "host.name:$HOST AND metricset.name:uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "table-old",
     "gridPos": { "h": 2, "w": 12, "x": 10, "y": 1 },
     "targets": [
      {
       "metrics": [
        {
         "$$hashKey": "object:324",
         "field": "system.core.id",
         "id": "8",
         "inlineScript": "_value + 1",
         "meta": {},
         "settings": { "size": 1 },
         "type": "raw_document"
        }
       ],
       "query": "host.name:$HOST AND service.type:system",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Load average - 1min",
     "type": "stat",
     "description": "Normalized value (aka value/cpu:s)",
     "gridPos": { "h": 4, "w": 3, "x": 1, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3303",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:3301",
         "field": "system.load.norm.1",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "host.name:$HOST AND event.dataset:system.load",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Load average - 5min",
     "type": "stat",
     "description": "Normalized value (aka value/cpu:s)",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3303",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:3301",
         "field": "system.load.norm.5",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "host.name:$HOST AND event.dataset:system.load",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Load average - 15min",
     "type": "stat",
     "description": "Normalized value (aka value/cpu:s)",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3415",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:3413",
         "field": "system.load.norm.15",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "host.name:$HOST AND event.dataset:system.load",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "table-old",
     "gridPos": { "h": 2, "w": 12, "x": 10, "y": 3 },
     "targets": [
      {
       "metrics": [
        {
         "$$hashKey": "object:324",
         "field": "system.core.id",
         "id": "8",
         "inlineScript": "_value + 1",
         "meta": {},
         "settings": { "size": 1 },
         "type": "raw_document"
        }
       ],
       "query": "host.name:$HOST AND metricset.name:cpu",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "table-old",
     "gridPos": { "h": 2, "w": 7, "x": 10, "y": 5 },
     "targets": [
      {
       "metrics": [
        {
         "$$hashKey": "object:324",
         "field": "system.core.id",
         "id": "8",
         "inlineScript": "_value + 1",
         "meta": {},
         "settings": { "size": 1 },
         "type": "raw_document"
        }
       ],
       "query": "host.name:$HOST AND metricset.name:memory",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "table-old",
     "gridPos": { "h": 2, "w": 5, "x": 17, "y": 5 },
     "targets": [
      {
       "metrics": [
        {
         "$$hashKey": "object:324",
         "field": "system.core.id",
         "id": "8",
         "inlineScript": "_value + 1",
         "meta": {},
         "settings": { "size": 1 },
         "type": "raw_document"
        }
       ],
       "query": "host.name:$HOST AND event.dataset:system.fsstat",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
     "content": " <small><b>Resolution</b> is <b>$interval</b>. This means that graph shows a metric for each $interval. The default resolution is \"auto\" which sets resolution to chosen time interval divided by 40, but you may set a manual value above. Note that resolution affects things like 'min', 'max' and 'current' values since these are based on metric values in the displayed graph. Combining a low value for resolution together with long time range will also consume much memory in your web browser and take long time to render.</small>"
    }
   ]
  },
  {
   "title": "CPU STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - utilization (%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "{{field}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:205",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:189",
         "field": "system.cpu.idle.pct",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:190",
         "field": "system.cpu.iowait.pct",
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:191",
         "field": "system.cpu.irq.pct",
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:192",
         "field": "system.cpu.nice.pct",
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:193",
         "field": "system.cpu.steal.pct",
         "id": "6",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:194",
         "field": "system.cpu.system.pct",
         "id": "7",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:195",
         "field": "system.cpu.user.pct",
         "id": "8",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:196",
         "field": "system.cpu.softirq.pct",
         "id": "9",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:cpu AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "CPU - load average (not normalized)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Load 1",
       "bucketAggs": [
        {
         "$$hashKey": "object:3829",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:3827",
         "field": "system.load.1",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:load AND host.name:$HOST",
       "timeField": "@timestamp"
      },
      {
       "alias": "Load 5",
       "bucketAggs": [
        {
         "$$hashKey": "object:3833",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:3831",
         "field": "system.load.5",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:load AND host.name:$HOST",
       "timeField": "@timestamp"
      },
      {
       "alias": "Load 15",
       "bucketAggs": [
        {
         "$$hashKey": "object:3837",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:3835",
         "field": "system.load.15",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:load AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORY STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{field}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:4470",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4466",
         "field": "system.memory.actual.used.bytes",
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:4467",
         "field": "system.memory.actual.free",
         "id": "6",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:memory AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Swap - usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{field}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:4531",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4527",
         "field": "system.memory.swap.used.bytes",
         "id": "5",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:4528",
         "field": "system.memory.swap.free",
         "id": "6",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:memory AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "PROCESS STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per process CPU - utilization (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "{{term process.name}}[{{term process.pid}}] User: {{user.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:4599",
         "fake": true,
         "field": "process.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5358",
         "fake": true,
         "field": "process.pid",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4600",
         "fake": true,
         "field": "user.name",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4601",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4596",
         "field": "system.process.cpu.total.norm.pct",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:process AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Per process RSS memory - usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{term process.name}}[{{term process.pid}}] User: {{user.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:5381",
         "fake": true,
         "field": "process.pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5382",
         "fake": true,
         "field": "process.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5383",
         "fake": true,
         "field": "user.name",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5384",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5379",
         "field": "system.process.memory.rss.bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:process AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "USER STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per user CPU - utilization (%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "User: {{user.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:5465",
         "fake": true,
         "field": "user.name",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5466",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5463",
         "field": "system.process.cpu.total.pct",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:process AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Per user RSS memory - usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "User: {{user.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:5522",
         "fake": true,
         "field": "user.name",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5523",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5520",
         "field": "system.process.memory.rss.bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:process AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FILESYSTEM STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem - usage (%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:5584",
         "fake": true,
         "field": "system.filesystem.mount_point",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5585",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5582",
         "field": "system.filesystem.used.pct",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:filesystem AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Filesystem - usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:5641",
         "fake": true,
         "field": "system.filesystem.mount_point",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5642",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5639",
         "field": "system.filesystem.used.bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "metricset.name:filesystem AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "DISK STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - I/O wait (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "read - {{term system.diskio.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:5716",
         "fake": true,
         "field": "system.diskio.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5717",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5712",
         "field": "system.diskio.read.time",
         "hide": true,
         "id": "1",
         "inlineScript": "_value / $__interval_ms",
         "meta": {},
         "settings": { "script": { "inline": "_value / $__interval_ms" } },
         "type": "max"
        },
        {
         "$$hashKey": "object:5713",
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:diskio AND host.name:$HOST",
       "timeField": "@timestamp"
      },
      {
       "alias": "write - {{term system.diskio.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:5724",
         "fake": true,
         "field": "system.diskio.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5725",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5720",
         "field": "system.diskio.write.time",
         "hide": true,
         "id": "1",
         "inlineScript": "_value / $__interval_ms",
         "meta": {},
         "settings": { "script": { "inline": "_value / $__interval_ms" } },
         "type": "max"
        },
        {
         "$$hashKey": "object:5721",
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:diskio AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Disk - I/O rate (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "read - {{term system.diskio.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:5827",
         "fake": true,
         "field": "system.diskio.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5828",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5823",
         "field": "system.diskio.read.bytes",
         "hide": true,
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "max"
        },
        {
         "$$hashKey": "object:5824",
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:diskio AND host.name:$HOST",
       "timeField": "@timestamp"
      },
      {
       "alias": "write - {{term system.diskio.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:5835",
         "fake": true,
         "field": "system.diskio.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5836",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5831",
         "field": "system.diskio.write.bytes",
         "hide": true,
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "max"
        },
        {
         "$$hashKey": "object:5832",
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:diskio AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Disk - I/O rate (iops)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "read - {{term system.diskio.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:5938",
         "fake": true,
         "field": "system.diskio.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5939",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5934",
         "field": "system.diskio.read.count",
         "hide": true,
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "max"
        },
        {
         "$$hashKey": "object:5935",
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.name:$HOST AND metricset.name:diskio",
       "timeField": "@timestamp"
      },
      {
       "alias": "write - {{term system.diskio.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:5946",
         "fake": true,
         "field": "system.diskio.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5947",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:5942",
         "field": "system.diskio.write.count",
         "hide": true,
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "max"
        },
        {
         "$$hashKey": "object:5943",
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.name:$HOST AND metricset.name:diskio",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "NETWORK STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Interface - I/O rate (bits)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "rx - {{term system.network.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:6057",
         "fake": true,
         "field": "system.network.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:6058",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:6053",
         "field": "system.network.in.bytes",
         "hide": true,
         "id": "1",
         "inlineScript": "(_value * 8 )/ ($__interval_ms / 1000)",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {
          "script": {
           "inline": "(_value * 8 )/ ($__interval_ms / 1000)"
          }
         },
         "type": "max"
        },
        {
         "$$hashKey": "object:6054",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:network AND host.name:$HOST",
       "timeField": "@timestamp"
      },
      {
       "alias": "tx - {{term system.network.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:6065",
         "fake": true,
         "field": "system.network.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:6066",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:6061",
         "field": "system.network.out.bytes",
         "hide": true,
         "id": "1",
         "inlineScript": "(_value * 8 )/ ($__interval_ms / 1000)",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {
          "script": {
           "inline": "(_value * 8 )/ ($__interval_ms / 1000)"
          }
         },
         "type": "max"
        },
        {
         "$$hashKey": "object:6062",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:network AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Network Interface - drops/errors (per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "rx drops - {{term system.network.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:6176",
         "fake": true,
         "field": "system.network.name",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:6177",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:6172",
         "field": "system.network.in.dropped",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "$$hashKey": "object:6173",
         "field": "1",
         "id": "4",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:network AND host.name:$HOST",
       "timeField": "@timestamp"
      },
      {
       "alias": "tx drops  - {{term system.network.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:6184",
         "fake": true,
         "field": "system.network.name",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:6185",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:6180",
         "field": "system.network.out.dropped",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "$$hashKey": "object:6181",
         "field": "1",
         "id": "4",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:network AND host.name:$HOST",
       "timeField": "@timestamp"
      },
      {
       "alias": "rx errors - {{term system.network.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:6192",
         "fake": true,
         "field": "system.network.name",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:6193",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:6188",
         "field": "system.network.in.errors",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "$$hashKey": "object:6189",
         "field": "1",
         "id": "4",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:network AND host.name:$HOST",
       "timeField": "@timestamp"
      },
      {
       "alias": "tx errors- {{term system.network.name}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:6200",
         "fake": true,
         "field": "system.network.name",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:6201",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 1 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:6196",
         "field": "system.network.out.errors",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "$$hashKey": "object:6197",
         "field": "1",
         "id": "4",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "metricset.name:network AND host.name:$HOST",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "LOGS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "syslogs from $HOST",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1234",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1158",
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "logs"
        }
       ],
       "query": "host.name:$HOST AND event.module:system",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}